# GitHub Sponsors configuration
# Uncomment and configure if you want to accept sponsorships

# github: [nooogle]
# patreon: # your_patreon_username
# open_collective: # your_open_collective_name
# ko_fi: # your_ko_fi_username
# tidelift: # your_tidelift_platform_name/package-name
# community_bridge: # your_community_bridge_project_name
# liberapay: # your_liberapay_username
# issuehunt: # your_issuehunt_username
# custom: # ['https://www.paypal.me/username', 'https://buy-me-a-coffee.com/username']
