name: Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report this issue!
  
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear description of what the bug is
      placeholder: What happened?
    validations:
      required: true
  
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Minimal code to reproduce the issue
      placeholder: |
        ```csharp
        var html = Generator.Create("Test")
            .AddParagraph("Example")
            .Generate();
        ```
    validations:
      required: true
  
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true
  
  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
    validations:
      required: true
  
  - type: input
    id: version
    attributes:
      label: Package Version
      description: Which version of CDS.FluentHtmlReports are you using?
      placeholder: e.g., 1.0.0
    validations:
      required: true
  
  - type: input
    id: dotnet-version
    attributes:
      label: .NET Version
      description: Which .NET version are you using?
      placeholder: e.g., .NET 8.0
    validations:
      required: true
  
  - type: input
    id: os
    attributes:
      label: Operating System
      description: Which OS are you running on?
      placeholder: e.g., Windows 11, Ubuntu 22.04, macOS 14
    validations:
      required: true
  
  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other information that might be helpful
